### PR TITLE
Update version to 1.4

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
Needed for https://github.com/conda-forge/staged-recipes/pull/2923

**Comment by jakirkham** [comment]
Might be good to re-render while you are at it.

**Comment by bgruening** [comment]
@jakirkham can we do this later? It blocks level 6 currently.

**Comment by bgruening** [comment]
ping @ocefpaf :)

**Comment by bgruening** [comment]
@ocefpaf thanks a lot!

**Comment by ocefpaf** [comment]
No problem. I could use more maintainers in all the r packages I am
maintaining  ;-p

**Comment by bgruening** [comment]
Add me and @johanneskoester if you like to all of them with the next rerendering.

**Pull request merged**
